### ISSUE TITLE
Ability to connect to desired namespace

### ISSUE THREAD

**Issue by gseshagirirao** [fidelity/kconnect#104]
Kconnect does not have the ability to connect to a namespace during a login process.  This feature will help us to login directly login into desired namespace rather than by default to "default" namespace and then switching. 

We would add something like --namespace option to the kconnect command and add it to the --help feature. 

Example: kconnect use eks --region us-east-2 --role-arn arn:aws:iam::XXXXX:role/EKS_Master --username XXXXX  --namespace my-namespace --alias pXXXX

**Comment by richardcase** [comment]
This is a great idea. Thanks @gseshagirirao

**Comment by arghya88** [comment]
So this means while generating the `kubeconfig` file add put the supplied namespace in the context?

**Comment by seankelly001** [comment]
If namespace is not specified, I'm assuming kconnect will run as normal. Would an ability to dynamically select the namespace from a list (similar to IAM role or region selection) be a useful feature, if an additional flag was passed (e.g. --set-namespace), or possibly if --namespace flag was set, but no value was supplied for it

**Comment by richardcase** [comment]
I think we should initially support setting a namespace via `--namespace` which the user will supply a value to and that will be added to the kubeconfig.

We could then create a separate issue to support prompting the users for a namespace from a list.

**Comment by arghya88** [comment]
I am interested to work on this.

**Comment by richardcase** [comment]
That would be great @arghya88. The development docs aren't  completed but i can help with any questions.

**Comment by richardcase** [comment]
@arghya88 - feel free to assign the issue to yourself.

**Comment by arghya88** [comment]
I could not assign..I guess there is no bot yet :)

**Comment by richardcase** [comment]
> @richardcase I could not assign..I guess there is no bot yet

Not yet....hopefully in time we can get prowbot or something similar. I manually assigned it to you

**Comment by arghya88** [comment]
@richardcase  should the namespace be set only for the current context of all contexts? I am thinking of following how we do taking the namespace as input as we do for `set-current` and modify the current context's namespace from `default` to the supplied value.

**Comment by richardcase** [comment]
>  should the namespace be set only for the current context or all contexts?

I think the namespace should only be set for the context that is created as a result of the `kconnect use` command.

> I am thinking of taking the namespace as input as we do for set-current and modify the current context's namespace from default to the supplied value.

This is would be great :+1:
