### ISSUE TITLE
AKS Discovery Plugin

### ISSUE THREAD

**Issue by richardcase** [fidelity/kconnect#11]
Create the discovery plugin for AKS clusters in Azure

**Comment by richardcase** [comment]
Create the discovery plugin for AKS clusters in Azure

**Comment by richardcase** [comment]
@arghya88 is going to work on this

**Comment by arghya88** [comment]
cc

**Comment by richardcase** [comment]
@arghya88 - how are you getting on with this? If you haven't had much time i can take it over if you want?

**Comment by richardcase** [comment]
Further to slack chat with @arghya88 i will take this on
