### ISSUE TITLE
https://kconnect.com

### ISSUE THREAD

**Issue by hnpandit** [fidelity/kconnect#111]
help documentation points to https://kconnect.com. Is this an internal website?

https://github.com/fidelity/kconnect/blob/main/docs/proposals/20200630-cli-ux.md

./kconnect -h [--help] or ./kconnect help

kconnect is a kubernetes connection manager CLI that helps sets up a connection to a k8s cluster using your identity provider credentials. Currently supports eks, aks and rancher more platforms.

You can find detailed documentation at https://kconnect.com

Usage:

**Comment by richardcase** [comment]
Thanks @hnpandit .

The `https://kconnect.com` website referred to in the proposal was for demonstration purposes only as the proposal was really to demonstrate the UX as part of the design.  

We hope to get a domain name soon and host our documents under this. We aren't quite there yet though i'm afraid.

I will update the UX docs to remove this confusion....thanks for raising this.
