### ISSUE TITLE
History output should indicate current context

### ISSUE THREAD

**Issue by richardcase** [fidelity/kconnect#123]
**Describe the solution you'd like:**
When using the table output format with `history ls` it should add an indicator to a row if its the current context for k8s.

**Why do you want this feature:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by arghya88** [comment]
@richardcase any example cli in `kubernetes` world which does this?

**Comment by richardcase** [comment]
> any example cli in `kubernetes` world which does this?

I haven't seen one i'm afraid @arghya88. I was thinking something along these lines:

- Lookup up the current context in the kubeconfig
- Get the history id from the extension of the context in the kubeconfig
- Then when we get the history list we can check if an entry has the same id and then add an indicator to the table row
