### ISSUE TITLE
EKS --region-filter flag

### ISSUE THREAD

**Issue by seankelly001** [fidelity/kconnect#125]
**Describe the solution you'd like:**
An additional flag for kconnect use eks, --region-filter
This will automatically filter region selection
e.g. kconnect use eks --region-filter us-

? Select a AWS region [Use arrows to move, type to filter]
> us-east-1
  us-east-2
  us-west-1
  us-west-2

**Why do you want this feature:**
Will be most useful in kconnect config.yaml, as many companies will only have cluster in us regions, eu regions etc

**Comment by arghya88** [comment]
Is it simillar to ` --role-filter` ?

**Comment by seankelly001** [comment]
@arghya88 Yes exactly!

**Comment by arghya88** [comment]
@seankelly001 But apparently the `--role-filter` is not implemented because I could not find any usage of this https://github.com/fidelity/kconnect/blob/main/pkg/plugins/discovery/aws/provider.go#L52

**Comment by arghya88** [comment]
@seankelly001 I am interested to work on `--role-filter` because it's not implemented.

**Comment by arghya88** [comment]
@richardcase is my understanding correct that `--role-filter` is not implemented even though it's there in UX?
