### ISSUE TITLE
make build fails for github.com/versent/saml2aws

### ISSUE THREAD

**Issue by arghya88** [fidelity/kconnect#131]
**What happened:**
[A clear and concise description of what the bug is.]

Running `make build` fails with below error

```
make build
CGO_ENABLED=0 go build -ldflags "-X github.com/fidelity/kconnect/internal/version.commitHash=8d9d146 -X github.com/fidelity/kconnect/internal/version.buildDate=2020-10-07T15:24:06Z" .
go: github.com/versent/saml2aws@v1.8.5-0.20200622110128-d94772688a70: parsing third_party/saml2aws/go.mod: open /Users/arghyasadhu/go/src/github.com/arghya88/kconnect/third_party/saml2aws/go.mod: no such file or directory
make: *** [build] Error 1
```

**What did you expect to happen:**

Make build to succeed

**How to reproduce it:**

Execute `make build` 
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
Mac OSX
- kconnect version (use `kconnect version`):
- Kubernetes version (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
- Target environment (e.g. EKS, AKS, Rancher):
- Authentication Used (e.g. SAML, IAM, Azure AD):

**Comment by arghya88** [comment]
Git cloning `https://github.com/Versent/saml2aws.git` into the `third_party` directory worked.

**Comment by richardcase** [comment]
This is because you need to initialise the submodule.....something that i need to add to the docs.

Can you run this and try again:

`git submodule update --init --recursive`

**Comment by arghya88** [comment]
@richardcase Yeah that worked. Thanks

**Comment by richardcase** [comment]
And thanks for the docs update @arghya88 👍
