### ISSUE TITLE
Azure AD Authentication Plugin

### ISSUE THREAD

**Issue by richardcase** [fidelity/kconnect#14]
Implement the Azure AD authentication plugin. We should probably replicate what `az login` does. See [this](https://github.com/Azure/azure-cli/blob/c508fa4aa181872c2ed2c7f53712e9d329d7a3f6/src/azure-cli-core/azure/cli/core/_profile.py#L832).

We should also support the azure environment authorizer, file authorizer and service principal. 

The Auth Code Flow that `az login` uses is very similar to the OAuth Auth Code Flow. This could potentially be re-used.

**Comment by arghya88** [comment]
@richardcase so we are looking at bringing in oauth  as an IDP ?

**Comment by richardcase** [comment]
> so we are looking at bringing in oauth as an IDP ?

@arghya88 -  yes for sure :+1: Is OAuth something you would want to use?

**Comment by arghya88** [comment]
I mean I was thinking how to make AKS work just like we have EKS today. Would SAML work with AKS or we need to make use of oauth instead of SAML for AKS?

**Comment by richardcase** [comment]
We need to implement a new Identity Provider for OAuth/AzureAD and then create the AKS cluster provider so that it uses the identity from the new identtity provider.

We also need a way for cluster providers to declare which identity providers they work with.
