### ISSUE TITLE
Shorten the context name in kubeconfig

### ISSUE THREAD

**Issue by kishoregv** [fidelity/kconnect#147]
**Describe the solution you'd like:**
Currently, the context name in kubeconfig is quite long as can seen in the below image. It is a little hard to read the the context name. It would be nice if the context name can be made shorter.
![image](https://user-images.githubusercontent.com/1823272/95747849-02b2de00-0c91-11eb-8c30-2a3442ae36e0.png)

**Why do you want this feature:**
Improves readability of the context name

**Comment by richardcase** [comment]
I think this is a good idea.

@kishoregv - if we removed `kconnect` from the context name would that we better? Or would that be too long still?

**Comment by kishoregv** [comment]
Removing kconnet helps. 
I am thinking removing timestamp and duplicated cluster name will help as well
`kconnect-kconnect-20201012121014-ecc-pe2-us-east-1@kconnect-eks-ecc-pe2-us-east-1`

**Comment by richardcase** [comment]
This was shortened as part of #153
