### ISSUE TITLE
History should be displayed sorted by LastUsed

### ISSUE THREAD

**Issue by richardcase** [fidelity/kconnect#156]
**Describe the solution you'd like:**
When using `kconnect ls` we should display the results sorted by **LastUsed** with the most recently used first.

**Why do you want this feature:**
As a user this is more intuitive

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by arghya88** [comment]
Maybe I can take a stab at this.

**Comment by arghya88** [comment]
@richardcase Looks to me just need to use `GetLastModified` instead of `GetAll` function from store. Wondering what should be the value of the parameter to `GetLastModified`.

**Comment by arghya88** [comment]
@seankelly001 that makes sense..I will implement it that way.Thanks
