### ISSUE TITLE
Kconnect prompts user input for role arn when --non-interactive flag is set

### ISSUE THREAD

**Issue by seankelly001** [fidelity/kconnect#165]
**What happened:**
I ran:
kconnect use eks --region us-east-1 --non-interactive
Note: I had username, password, and IDP settings in config

I was then prompted for role arn

**What did you expect to happen:**
For kconnect to fail immediately, and to show that roleArn is required

**How to reproduce it:**
Run kcoonect use eks with all parameters required except --roleArn, and with --non-interactive

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- kconnect version (use `kconnect version`): 2.0.0
- Kubernetes version (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): linux
- Target environment (e.g. EKS, AKS, Rancher): EKS
- Authentication Used (e.g. SAML, IAM, Azure AD): SAML

**Comment by arghya88** [comment]
@seankelly001 I can give this a shot.

**Comment by arghya88** [comment]
@seankelly001 I have not been able to make progress on this and would like to hand it back to you.

**Comment by richardcase** [comment]
Thanks @arghya88 - i have unaasigned you.

**Comment by richardcase** [comment]
This should be fixed in 0.5 due to #291
