### ISSUE TITLE
Add a flag to ignore alias prompt

### ISSUE THREAD

**Issue by kishoregv** [fidelity/kconnect#179]
**Describe the solution you'd like:**
Add a flag to ignore alias, so that user won't be prompted for alias.

**Why do you want this feature:**
Prompt is not desired in non-interactive mode when used in automation. 
Alternatively user can be forced to pass an alias every time even though alias is not really useful in the case of automation.

Just opening a discussion

**Comment by richardcase** [comment]
Thanbks @kishoregv. I agree that alias prompt should only be shown in the interactive mode.

When running with `--non-interactive` it should not ask for the alias and if it does this is a bug

**Comment by richardcase** [comment]
I will investigate this.

**Comment by kishoregv** [comment]
@richardcase Sorry, I have missed the flag. When running with --non-interactive flag it works as expected.

Thanks for the info
