### ISSUE TITLE
Error when trying to run kconnect just after installation.

### ISSUE THREAD

**Issue by avacaru** [fidelity/kconnect#184]
**What happened:**
kconnect fails to configure logging and fails with error. (~/.kconnect/config.yaml doesn't exist)

**What did you expect to happen:**
running `kconnect` should have displayed the help message

**How to reproduce it:**
Download kconnect_linux.tar.gz, untar, run `./kconnect`. This happens in the docker image as well.
```
$> docker run --rm -it kconnectcli/kconnect
2020/11/10 13:19:28 failed to configure logging getting verbosity flag: creating application configuration: creating empty config file /home/nonroot/.kconnect/config.yaml: open /home/nonroot/.kconnect/config.yaml: no such file or directory
$> docker run --rm -it kconnectcli/kconnect kconnect
2020/11/10 13:22:28 failed to configure logging getting verbosity flag: creating application configuration: creating empty config file /home/nonroot/.kconnect/config.yaml: open /home/nonroot/.kconnect/config.yaml: no such file or directory
$> ./kconnect
2020/11/10 13:24:00 failed to configure logging getting verbosity flag: creating application configuration: creating empty config file /home/user/.kconnect/config.yaml: open /home/user/.kconnect/config.yaml: no such file or directory
```

**Anything else you would like to add:**
Note that the system I was running this on did not have the ~/.kconnect directory created. I would have expected kconnect to create it if not there.

**Environment:**

- kconnect version (use `kconnect version`): 0.2.1
- Kubernetes version (use `kubectl version`): -
- OS (e.g. from `/etc/os-release`): linux/docker
- Target environment (e.g. EKS, AKS, Rancher): -
- Authentication Used (e.g. SAML, IAM, Azure AD): -

**Comment by richardcase** [comment]
Thanks for raising this @avacaru .

Could you try the following to see if it creates the folder for you:

```bash
docker pull docker.io/kconnectcli/kconnect:latest
docker run -v ~/:/home/nonroot/ kconnect:latest use eks --idp-protocol saml
```

**Comment by seankelly001** [comment]
This is not just a docker issue, also presents itself with using CLI for the first time
