### ISSUE TITLE
Duplicate alias on 'kconnect to' login with --namespace flag

### ISSUE THREAD

**Issue by tckeith** [fidelity/kconnect#187]
**What happened:**
[A clear and concise description of what the bug is.]
Utilizing an alias for 'kconnect to {alias-name}' creates a duplicate entry in history.yaml when the namespace flag is used with kconnect use eks. All attempts to reconnect using that alias fail with the following message "fatal  failed executing root command   {"error": "getting history entry: getting history entry by alias: duplicate alias detected"}"

**What did you expect to happen:**
duplicate alias are not created when using kconnect to connect using an alias

**How to reproduce it:**
> kconnect use eks --namespace {namespace-name} _supply alias name_
> kconntect to {different-alias]
> kconntect to {alias-name]
>> fatal  failed executing root command   {"error": "getting history entry: getting history entry by alias: duplicate alias detected"}

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

kconnect version
info   kconnect - the kubernetes cli   {"version": "0.2.1"}
version: 0.2.1
builddate: "2020-10-20T08:36:51Z"
commithash: d35f6547d69123ace0d53d16c5fe4f5b6f4ded80
goversion: go1.13.15
platform: windows/amd64
compiler: gc

k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18363 N/A Build 18363

- Target environment: EKS
- Authentication Used (e.g. SAML, IAM, Azure AD):  SAML

**Comment by richardcase** [comment]
Thanks @tckeith - i will investigate

**Comment by seankelly001** [comment]
I think this was closed in #170

**Comment by richardcase** [comment]
Yes i think this is fixed now.

@tckeith - the latest version should fix this.

**Comment by richardcase** [comment]
Closing as it was fixed in #170
