### ISSUE TITLE
add feature kconnect logout 

### ISSUE THREAD

**Issue by ashishapy** [fidelity/kconnect#197]
**Describe the solution you'd like:**
Provide option to logout from current logged-in cluster. $ kconnect logout should just clear the auth creds, e.g. in EKS just clear AWS sts token. 

**Why do you want this feature:**
kconnect helps connecting multiple clusters & sometime unintentionally kubectl run might cause unintentional change to the existing cluster. kconnect logout can help cluster admins to logout from cluster.

**Anything else you would like to add:**
No

**Comment by seankelly001** [comment]
Great idea :)

**Comment by richardcase** [comment]
Thanks @ashishapy - a very good idea.
