### ISSUE TITLE
issue with kconnect 0.4.0 on ubuntu

### ISSUE THREAD

**Issue by ashishapy** [fidelity/kconnect#255]
**What happened:**
kconnect throwing error on ubuntu.

**What did you expect to happen:**
NO error

**How to reproduce it:**
$ kconnect version
info    kconnect - the Kubernetes Connection Manager CLI        {"version": "0.4.0"}
version: 0.4.0
builddate: "2020-12-21T16:21:00Z"
commithash: 473de0b6fd68af08279b42f6c1306597de64e402
goversion: go1.13.15
platform: linux/amd64
compiler: gc

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb540a6]

goroutine 1 [running]:
github.com/fidelity/kconnect/internal/commands.reportNewerVersion(0x1442a00, 0xc000102018)
        /home/runner/work/kconnect/kconnect/internal/commands/root.go:272 +0xfe6
github.com/fidelity/kconnect/internal/commands.RootCmd.func3(0xc00049b600, 0x1c26538, 0x0, 0x0, 0x0, 0x0)
        /home/runner/work/kconnect/kconnect/internal/commands/root.go:139 +0x10d
github.com/spf13/cobra.(*Command).execute(0xc00049b600, 0x1c26538, 0x0, 0x0, 0xc00049b600, 0x1c26538)
        /home/runner/go/pkg/mod/github.com/richardcase/cobra@v1.0.1-0.20200717133916-3a09287ba25e/command.go:870 +0x38a
github.com/spf13/cobra.(*Command).ExecuteC(0xc00049a000, 0x0, 0x0, 0x11)
        /home/runner/go/pkg/mod/github.com/richardcase/cobra@v1.0.1-0.20200717133916-3a09287ba25e/command.go:963 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/richardcase/cobra@v1.0.1-0.20200717133916-3a09287ba25e/command.go:900
main.main()
        /home/runner/work/kconnect/kconnect/main.go:47 +0x4aa

**Environment:**
- OS (e.g. from `/etc/os-release`):
- $ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by richardcase** [comment]
Investigating this now

**Comment by richardcase** [comment]
I just tried on mt ubuntu dev machine and it works for me:

![image](https://user-images.githubusercontent.com/198425/103519763-01e3af80-4e6e-11eb-97e3-c6343a9f87bd.png)

**Comment by richardcase** [comment]
@ashishapy - is this a first time install or have you previously run kconnect prior to 0.4.0?

**Comment by ashishapy** [comment]
It is not first time. kconnect has been working form me till 
$ _kconnect version
info    kconnect - the Kubernetes Connection Manager CLI        {"version": "0.3.1"}
version: 0.3.1
builddate: "2020-11-26T15:47:47Z"
commithash: 2acaa1aa1c0dbb00f9e8c17cde8f5f67cc357a14
goversion: go1.13.15
platform: linux/amd64
compiler: gc_

_But broke with kconnect 0.4.0 version

**Comment by ashishapy** [comment]
I think I tried kconnect 0.4.0 install with brew & stand-alone binary both. None of these install version works for me on ubuntu.
I tried on windows ubuntu WSL & ubuntu VM both.

**Comment by ashishapy** [comment]
> I just tried on mt ubuntu dev machine and it works for me:
> 
> ![image](https://user-images.githubusercontent.com/198425/103519763-01e3af80-4e6e-11eb-97e3-c6343a9f87bd.png)

Are you on Ubuntu 18?

**Comment by richardcase** [comment]
I'm using Ubuntu 20.10, I'll try an older version of Ubuntu along with having a previous version installed. I'll let you know if I can recreate it

**Comment by richardcase** [comment]
@ashishapy - i tried on ubuntu 18.04 and with different version and I can't recreate the issue.  Looking at the stack trace in your error its failing when we do the check for a newer version. 

Do you have anything in `~/.kconnect/config.yaml`? Also, if I build a version with extra debugging would be able to test it?

**Comment by ashishapy** [comment]
```
cat ~/.kconnect/config.yaml
apiVersion: kconnect.fidelity.github.com/v1alpha1
kind: Configuration
spec:
  providers:
    aks:
      idp-protocol: aad
      tenant-id: 7521acbc-a68c-41e5-a975-1cf83066dd19
    eks:
      idp-endpoint: <REDACTED>
      idp-protocol: saml
      idp-provider: PingNTLM
      region-filter: us-
  versionCheck:
    lastVersionCheck: "2020-12-23T10:53:15Z"
```

Yes, I can test with debug flag. Have you upgraded any internal tools or golang version in new release?
