### ISSUE TITLE
Configuration via file (with default location)

### ISSUE THREAD

**Issue by richardcase** [fidelity/kconnect#28]
**Describe the solution you'd like:**
I want to be able to supply configuration via a config file. It should look for a default config file in $HOME/.kconnect/config

**Why do you want this feature:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by nipuna-perera** [comment]
@richardcase I would love to contribute to this and would like to start with something small. I am a newbie to contributing to github projects. How do I assign an issue to myself? or mark an issue as in-progress?

**Comment by richardcase** [comment]
Hey @nipuna-perera 👋🏼 that would be great if you wanted to contribute. Could you give me a week to get the project into a position where it’s easier for people to contribute? I can also write the contributing guide.

**Comment by nipuna-perera** [comment]
@richardcase yes of course! If you need help with structuring the project or creating the contributing guide, I can do that as well. Let me know. I was anyway hoping to create a contribution guide based on my experience with the initial contribution 😄
