### ISSUE TITLE
Add support for interacting with kconnect through a `SDK`

### ISSUE THREAD

**Issue by AidanFogarty** [fidelity/kconnect#286]
**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]
At the moment, kconnect offers the ability to authenticate and discover clusters through the cli tool. It would be nice to have the ability to import kconnect as a Go package and call methods to authenticate/discover clusters, particularly for EKS clusters.  

**Why do you want this feature:**
We are currently executing kconnect in our app by utilizing the `os/exec` Go package to run the cli command. Being able to import kconnect and call methods directly natively would allow for more control instead having to execute kconnect as a sub process. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by richardcase** [comment]
Thanks @AidanFogarty . This seems like a good idea and would be fairly easy for us to do. I will add it to the next release.

**Comment by ramnar** [comment]
We are having similar challenge, but in Python. We are using kconnect in our python module  as a binary. How about python wrapper for the go module of kconnect ? @richardcase https://github.com/go-python/gopy

**Comment by richardcase** [comment]
@ramnar  - thats interesting. I'll refactor the code to make reusing the core functionality possible and then we can look at this.

**Comment by richardcase** [comment]
This will be available in the 0.5 release as #291 was a refactor to enable this.

**Comment by richardcase** [comment]
Closing as this is in the 0.5.0 release
