### ISSUE TITLE
install script failing to install dependencies

### ISSUE THREAD

**Issue by divyam234** [fidelity/kconnect#340]
This is mainly due to use of github api in fetching latest version which has some sort of rate limitation. Install script is failing in various build agents behind corporate proxy . I would recommend to fetch  latest version calling webpage instead.

**Comment by rajarajanpsj** [comment]
@divyam234  Tagging @seankelly001  Can you take a look at this

**Comment by divyam234** [comment]
@rajarajanpsj  within fidelity and it should be valid outside fidelity  also  as build agents are using http proxies with limited pool of ips . Github api has rate limit of 5000 calls per hour beyond that it will fail to respond.

**Comment by richardcase** [comment]
The other option is that we could also check for the existence of a github token and use that if specified so that the rate limits are higher.

**Comment by divyam234** [comment]
https://github.com/fidelity/kconnect/pull/356
