### ISSUE TITLE
Disable update check via config file

### ISSUE THREAD

**Issue by leosenthi** [fidelity/kconnect#344]
**Describe the solution you'd like:**
I like to disable update check permanently through config file.

**Why do you want this feature:**

The corporate isolated environments may not have have access to api.github.com to check update every time.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by srinathanand** [comment]
@leosenthi 
There is a `--no-version-check   If set to true kconnect will not check for a newer version` already included in the flags. Using that should prevent `kconnect` from checking for a newer version.
