### ISSUE TITLE
set AWS_SHARED_CREDENTIALS_FILE for eks in kubeconfig ENV var

### ISSUE THREAD

**Issue by ashishapy** [fidelity/kconnect#388]
**Describe the solution you'd like:**
in case of EKS, set AWS_SHARED_CREDENTIALS_FILE env var in kubeconfig along with AWS_PROFILE in env var

**Why do you want this feature:**
In case user wants to store AWS creds to any other location, then kubectl (with aws-iam-authenticator) will fail authentication because without AWS_SHARED_CREDENTIALS_FILE in kubeconfig env var, it will search at default location.

**Anything else you would like to add:**
This will also help when there is many user sessions on same machine or Docker container.

**Comment by ashishapy** [comment]
@seankelly001 Which kconnect version will it be part of?

**Comment by seankelly001** [comment]
> @seankelly001 Which kconnect version will it be part of?

It will be part of 0.5.6, which will be released in a few weeks time
