### ISSUE TITLE
kconnect use eks pulls a config with client.authentication.k8s.io/v1beta1

### ISSUE THREAD

**Issue by Newfid** [fidelity/kconnect#393]
downloaded kconnect and logged in to eks.  when running any kubectl commands seeing errors - the KUBECONFIG file looks to have v1beta1 and v1alpha that is messing up 
kubectl get namespaces
Unable to connect to the server: getting credentials: exec plugin is configured to use API version client.authentication.k8s.io/v1beta1, plugin returned version client.authentication.k8s.io/v1alpha1

**Comment by seankelly001** [comment]
Hi @Newfid, you need to have aws-iam-authenticator version >= v0.5.5

https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/tag/v0.5.5

We have just updated the docs to reflect this:
https://github.com/fidelity/kconnect/pull/391/commits/3f11d016cfad89d067871eb88472cc331b8a0193
