### ISSUE TITLE
Passing a kube config doesn't seem to work

### ISSUE THREAD

**Issue by ltsz16** [fidelity/kconnect#414]
I run the connect piece and everything per the documentation and I check the logs (see below). If you notice in the connection I set the role to My_Role but when the api runs it says it cannot because the role (ADifferentRuntimeRole) doesn't have permission.  Why isn't kconnect using the role I passed to it?

My code output:

kubeconf_path = '/home/sst_user/.kube/config'

AWS_SHARED_CREDENTIALS_FILE=/home/sst_user/.aws/credentials /home/sst_user/app/kconn/kconnect/kconnect use eks --cluster-id=arn:aws:eks:us-east-1:12345678:cluster/rest_my_clusterid --region=us-east-1 --role-arn=arn:aws:iam::12345678:role/My_Role --username=****** --password=***** --namespace=my_namespacee\ --kubeconfig=/home/sst_user/.kube/config --no-input --no-history --no-version-check --idp-protocol saml --idp-endpoint https://pfprd.fmr.com/ --idp-provider PingNTLM

withopen(kubeconf_path, "a+") as f:
    print(f"Writing to {​​​​​​​​kubeconf_path}​​​​​​​​")
    f.write(' - name: AWS_SHARED_CREDENTIALS_FILE\n')
    f.write(' value: ' + awscred_path)

os.environ["KUBECONFIG"]=kubeconf_path  
config.load_kube_config(config_file=kubeconf_path)
v2 = client.AppsV1Api()
api_response = v2.patch_namespaced_deployment_scale(data.deployid,data.namespace,{​​​​​​​​'spec': {​​​​​​​​'replicas': nu_pods}​​​​​​​​}​​​​​​​​)

Return message: is forbidden: User \"arn:aws:iam::12345678:role/ADifferentRuntimeRole\" cannot patch resource \"deployments/scale\  

Where is it getting that role APSSelfServiceRuntimeRole? It seems like it should use what I set in the connection.  How can I ensure the kconnect config is being used if not by the config.load_kube_config?

**Environment:**
Inside the \<fidelty-image-registry\>/selfservice-base docker image

- kconnect version 0.5.5
- Kubernetes version: Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-eks-0d102a7", GitCommit:"eb09fc479c1b2bfcc35c47416efb36f1b9052d58", GitTreeState:"clean", BuildDate:"2022-02-17T16:36:28Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
 
- Target environment: EKS
_ OS: NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.14.3
PRETTY_NAME="Alpine Linux v3.14"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

**Comment by seankelly001** [comment]
Hi @ltsz16 , could you edit your comment to remove references to specific AWS accounts + roles please? For a substitute you can just put something like:  arn:aws:iam::1111111111111:role/MyRole

**Comment by ltsz16** [comment]
Done

**Comment by ltsz16** [comment]
Is there an estimate on when this might be addressed?

**Comment by Gearheads** [comment]
After much discussion, we were able to get it working, and concluded that the issue was a misconfiguration.

There might have been multiple `KUBECONFIG` files, and/or the `KUBECONFIG` environment variable was misconfigured, which would explain why kconnect was using the incorrect role.
