### ISSUE TITLE
Windows Git Bash Returns Error

### ISSUE THREAD

**Issue by Gearheads** [fidelity/kconnect#439]
**What happened:**
[A clear and concise description of what the bug is.]
There appears to be some kind of issue when users try using `kconnect` on a `Windows` machine within a `Git Bash` terminal.

**What did you expect to happen:**
We would expect `kconnect` to run successfully on Windows within a Git Bash terminal.

**How to reproduce it:**
- Have a Windows machine
- Open Git Bash
- Run `kconnect use eks`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
This is the error message `kconnect` throws:
```
fatal   failed executing root command   {"error": "authenticating using provider saml:
 binding and validation config: validating config struct:
 Key: 'ProviderConfig.IdentityProviderConfig.Username' Error:Field validation for 'Username' failed on the
 'required' tag\nKey: 'ProviderConfig.IdentityProviderConfig.Password' Error:Field validation for 'Password'
 failed on the 'required' tag"}
main.main
        /home/runner/work/kconnect/kconnect/cmd/kconnect/main.go:50
runtime.main
        /opt/hostedtoolcache/go/1.17.11/x64/src/runtime/proc.go:255
```

**Environment:**

- kconnect version (use `kconnect version`): `0.5.5` or `0.5.7`
- Kubernetes version (use `kubectl version`): `1.20` or `1.21`
- OS (e.g. from `/etc/os-release`): Windows
- Target environment (e.g. EKS, AKS, Rancher): EKS, potentially AKS and RKS.
- Authentication Used (e.g. SAML, IAM, Azure AD): SAML

**Comment by jacobfra** [comment]
I was able to reproduce this issue on my fidelity laptop..
in a gitbash terminal on windows...
$ ls -l
total 108572
-rwxr-xr-x 1 A309645 1049089 46422016 Oct 20 15:07 aws-iam-authenticator.exe*
-rwxr-xr-x 1 A309645 1049089 18924032 Oct 20 15:04 kconnect.exe*
-rwxr-xr-x 1 A309645 1049089 45722624 Oct 20 15:06 kubectl.exe*

$ kconnect use eks --region us-east-1 --role-arn <arn> --username <user> --password <pass> ==> this appears to work however when just do...

$ kconnect use eks
... you get error and not a display of aws regions...
fatal   failed executing root command   {"error": "authenticating using provider saml: binding and validation config: validating config struct: Key: 'ProviderConfig.IdentityProviderConfig.Username' Error:Field validation for 'Username' failed on the 'required' tag\nKey: 'ProviderConfig.IdentityProviderConfig.Password' Error:Field validation for 'Password' failed on the 'required' tag"}

**Comment by jacobfra** [comment]
This issue has to do with the use of this code as a dependency.  https://github.com/AlecAivazis/survey.    there is a current issue https://github.com/AlecAivazis/survey/issues/148  where it is not supported in gitbash for windows which uses Mingw64.  Right now if you want to run in interactive mode it will not be able to prompt you for choices and therefore cannot input data into the validating functions.
