### ISSUE TITLE
IAM Authentication error 

### ISSUE THREAD

**Issue by Nanmozhi22** [fidelity/kconnect#456]
**What happened:**
[We are conducting EKS workshop on monthly basis. Our participants are following below kconnect install instructions to connect k8s cluster , out 50 participants minimum 3 to 4 users are experiencing an issue in connecting to cluster and getting the below error 

**Error:** 
"Unable to connect to the server: getting credentials: exec: executable aws-iam-authenticator not found".  As a work around user had to downgrade iam authenticator to version 0.5.5 but the latest is 0.5.9

**Environment:** Dev

- OS (e.g. from `/etc/os-release`): 
- Target environment (e.g. EKS, AKS, Rancher): EKS
- Authentication Used (e.g. SAML, IAM, Azure AD):  IAM

**Comment by Gearheads** [comment]
Hi @Nanmozhi22, I don't think this is a bug with kconnect.

`Unable to connect to the server: getting credentials: exec: executable aws-iam-authenticator not found` usually means that the user did not setup the terminal PATH correctly, and they need to do something like the following in order for the "kconnect" directory to be resolvable:
```
For MacOS/Linux:
export PATH=$PATH:/path/to/kconnect

For Windows (Git Bash):
export PATH=$PATH:"/C/path/to/kconnect"

For Windows (Cmd/Powershell):
set PATH=%PATH%:"C:\path\to\kconnect"
```

Please correct me if I am misunderstanding the issue.

**Comment by Gearheads** [comment]
Closing for now
