### ISSUE TITLE
Log level not set correctly

### ISSUE THREAD

**Issue by richardcase** [fidelity/kconnect#53]
**What happened:**
I am trying to set the log level to debug using `--log-level DEBUG` but no debug logs are output.

**What did you expect to happen:**
I expect to see DEBUG log entries

**How to reproduce it:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- kconnect version (use `kconnect version`):
```bash
version: 0.0.1-rc.1
builddate: "2020-08-05T12:25:39Z"
commithash: a0c7778253552629a6770e4ec3caddf9dd3c7c64
goversion: go1.13.14
platform: darwin/amd64
compiler: gc
```
- Kubernetes version (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): Mac
- Target environment (e.g. EKS, AKS, Rancher): EKS
- Authentication Used (e.g. SAML, IAM, Azure AD): SAML

**Comment by nipuna-perera** [comment]
Hi @richardcase do you think the project is ready for contributions?

**Comment by richardcase** [comment]
@nipuna-perera - yes I think it's in a good place to start contributing. Would you like to work on this?

**Comment by richardcase** [comment]
@nipuna-perera - i've just added a basic contributing guide. I'd be keen to improve based on your feedback if you decide to work on this issue.

**Comment by nipuna-perera** [comment]
@richardcase Yes I would like to work on this. I see the contribution guide. I will review it and get back to you.

**Comment by richardcase** [comment]
> Yes I would like to work on this. I see the contribution guide. I will review it and get back to you.

Thanks @nipuna-perera - i assigned the issue to you. Let me know if you need any help.
