### ISSUE TITLE
Remove duplicate word in initial design documentation

### ISSUE THREAD

**Issue by shijiadong2022** [fidelity/kconnect#563]
**What happened:**
This is to remove duplicate word in the initial design documentation - https://github.com/fidelity/kconnect/blob/main/docs/proposals/20200607-initial-design.md

**What did you expect to happen:**
Remove duplicate 'get get' 
> There doesn't exist a good open source solution that based on your user credentials (i.e. SAML, OAuth2/OIDC, IAM) will discover what Kuberneres clusters you have access to and how to get get the kubeconfig file for a cluster you have access to.

**Comment by puneetkumar712** [comment]
I will be working on fixing this documentation
