### ISSUE TITLE
broken links in document

### ISSUE THREAD

**Issue by shijiadong2022** [fidelity/kconnect#584]
**What happened:**
high level design and sequence diagrams cannot be loaded in the https://github.com/fidelity/kconnect/blob/main/docs/proposals/20200607-initial-design.md document.

**What did you expect to happen:**
The two diagrams are visible in the document.

**How to reproduce it:**
The two diagrams are not showing in the Proposal/Design section of this document - https://github.com/fidelity/kconnect/blob/main/docs/proposals/20200607-initial-design.md

**Anything else you would like to add:**

**Environment:**

- kconnect version (use `kconnect version`):
- Kubernetes version (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
- Target environment (e.g. EKS, AKS, Rancher):
- Authentication Used (e.g. SAML, IAM, Azure AD):

**Comment by puneetgared** [comment]
Working on this one
