### ISSUE TITLE
Remove duplicate word in design document

### ISSUE THREAD

**Issue by AnshuChadha** [fidelity/kconnect#598]
**What happened:**
[A clear and concise description of what the bug is.]
https://github.com/fidelity/kconnect/blob/main/docs/proposals/20200607-initial-design.md

Design document contains duplicate word **choosing** 

**What did you expect to happen:**
Remove duplicate word choosing from design document you can choose to regenerate the kubeconfig by **choosing choosing** a item from your history

**How to reproduce it:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- kconnect version (use `kconnect version`):
- Kubernetes version (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
- Target environment (e.g. EKS, AKS, Rancher):
- Authentication Used (e.g. SAML, IAM, Azure AD):

**Comment by puneetgared** [comment]
Working on this one
