### ISSUE TITLE
K8s python client failing to load_kube_config generated with newer versions of kconnect later than 0.5.10

### ISSUE THREAD

**Issue by subrat0130** [fidelity/kconnect#614]
**What happened:**
We use Kubernetes python client to perform operations on our EKS clusters. With the version of kconnect later than 0.5.10 kubernetes python client fails to perform load_kube_config with the error as:
`while parsing a block mapping
  in "/home/appuser/.kube/27ec83ee-a1f3-4dd6-9c18-8361b55ddbc0", line 20, column 7
expected <block end>, but found '-'
  in "/home/appuser/.kube/27ec83ee-a1f3-4dd6-9c18-8361b55ddbc0", line 32, column 7 `

**What did you expect to happen:**
Kubernetes python client to work seamlessly with the newer versions of kconnect

**How to reproduce it:**
Use kconnect version later than 0.5.10, connect to cluster and use kubernets python client load_kube_config function

**Anything else you would like to add:**
We notice a new line "provideClusterInfo: false" being added to the config file which wasn't the case earlier.

**Environment:**

- kconnect version (use `kconnect version`): 0.5.10
- Kubernetes version (use `kubectl version`): 1.28.3
- Target environment (e.g. EKS, AKS, Rancher): EKS
- Authentication Used (e.g. SAML, IAM, Azure AD): IAM
-  Kubernetes python client version: 28.1.0

**Comment by subrat0130** [comment]
not an issue from kconnect

**Comment by Gearheads** [comment]
For reference, we determined the issue was some custom logic within a Python script:
```
with open(kubeconf_path, "a+") as f:
            f.write('      - name: AWS_SHARED_CREDENTIALS_FILE\n')
            f.write('        value: ' + awscred_path)
```
This snippet was causing the `KUBECONFIG` file to be invalid.
