### ISSUE TITLE
Homebrew formula updated before binary is available

### ISSUE THREAD

**Issue by davidfmatheson** [fidelity/kconnect#666]
**What happened:**
The Homebrew [formula for kconnect](https://github.com/fidelity/homebrew-tap/blob/master/Formula/kconnect.rb) was updated to 0.5.16 last week, but that binary does not seem to be available. The kconnect page lists 0.5.15 as the latest release. This causes kconnect installation through homebrew to fail.

**What did you expect to happen:**
`brew install fidelity/tap/kconnect` should succeed

**How to reproduce it:**
Run `brew install fidelity/tap/kconnect`

**Comment by Gearheads** [comment]
Working on creating a new release.

**Comment by Gearheads** [comment]
Release `0.5.16` has been created: https://github.com/fidelity/kconnect/releases/tag/0.5.16

Also, can confirm that `brew install fidelity/tap/kconnect` completes successfully.
