### ISSUE TITLE
Extract base ping url from user input

### ISSUE THREAD

**Issue by seankelly001** [fidelity/kconnect#67]
Problem
Entering the full url for --idp-endpoint can cause kconnect to fail, as it automatically appends  "/idp/startSSO.ping?" to the url

Example:
"https://pfprd.fmr.com/idp/startSSO.ping" fails, but: just "https://pfprd.fmr.com" works

Solution:
If the url ends with "idp/startSSO.ping", do not append it, so both versions of the url would work

**Why do you want this feature:**
Will make the CLI more user friendly

**Comment by richardcase** [comment]
This is not something we can easily do that will work across all the idp-providers as we use the saml2aws package and the patterns are not exposed.

If you use the GoogleApps provider then it appends query string items, so we'd need to support multiple mechanisms.

We could add our own "pre-processor" that does this but we'd have to keep that inline with the package we use.

Personally i would prefer to solve this via documentation and perhaps extra documentation on the interactive prompt as well.

**Comment by richardcase** [comment]
Closing after discussion with @seankelly001
